#!/bin/bash

echo ""
echo "--------------------------------------------------------------------------------"
echo "Deploying app with the following commit message:"
echo "'$1'"
echo "--------------------------------------------------------------------------------"

yarn build

git add .
git commit -m "$1"
git push

cp -rf ./build/ ~/Projects/thomasmcevoy.github.com/531-react/
cd ../thomasmcevoy.github.com

git add .
git commit -m "$1"
git push
