#!/bin/bash

echo ""
echo "--------------------------------------------------------------------------------"
echo "Deploying app with the following commit message:"
echo "'$1'"
echo "--------------------------------------------------------------------------------"

yarn build

git add .
git commit -m "$1"
git push

cp -rf ./build/ ~/Projects/thomas-mcevoy.com/dist/531/
cd ../thomas-mcevoy.com

git add .
git commit -m "$1"
git push
